using DevExpress.DataAccess.Sql;
using DevExpress.XtraEditors;
using DevExpress.XtraGrid.EditForm.Helpers.Controls;
using DevExpress.XtraGrid.Views.Grid;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Windows.Forms;
using TOP.lib;

namespace TOP.MngFrm
{
    public partial class mFrmClient : TOP.Parent.PForm
    {
        public mFrmClient()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource asynchronously
           // sqlDataSource1.FillAsync();
        }



        private void qry_cod01m00()
        {

            sqlDataSource2.Fill("QRY_COD01M00");
            DataTable dt = CUtil.GetTable(sqlDataSource2.Result["QRY_COD01M00"]);
            gridControl1.DataSource = dt;

        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            qry_cod01m00();
            
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            gridView1.AddNewRow();
        }

        private void gridView1_ShowingPopupEditForm(object sender, DevExpress.XtraGrid.Views.Grid.ShowingPopupEditFormEventArgs e)
        {

            
            foreach (Control control in e.EditForm.Controls)
            {
                if (!(control is EditFormContainer))
                {
                    continue;
                }
                foreach (Control nestedControl in control.Controls)
                {
                    if (!(nestedControl is PanelControl))
                    {
                        continue;
                    }
                    foreach (Control button in nestedControl.Controls)
                    {
                        if (!(button is SimpleButton))
                        {
                            continue;
                        }
                        var simpleButton = button as SimpleButton;
                        simpleButton.Click -= editFormUpdateButton_Click;
                        simpleButton.Click += editFormUpdateButton_Click;
                    }
                }
            }
        }

        private void editFormUpdateButton_Click(object sender, EventArgs e)
        {
            DataRow dr = gridView1.GetFocusedDataRow();

            try
            {

                if (dr.RowState == DataRowState.Added)
                {
                    //insert 버튼으로 열었으면 신규 추가를 시도하고

                    sqlDataSource3.Queries["INSERT_COD01M00"].Parameters.Find(x => x.Name == "P_CLIENT_NM").Value = dr["CLIENT_NM"].ToString();
                    sqlDataSource3.Queries["INSERT_COD01M00"].Parameters.Find(x => x.Name == "P_TEL_NO").Value = dr["TEL_NO"].ToString();
                    sqlDataSource3.Queries["INSERT_COD01M00"].Parameters.Find(x => x.Name == "P_FAX_NO").Value = dr["FAX_NO"].ToString();
                    sqlDataSource3.Queries["INSERT_COD01M00"].Parameters.Find(x => x.Name == "P_DESCRIPT").Value = dr["DESCRIPT"].ToString();


                    SqlDataSource.DisableCustomQueryValidation = true;

                    sqlDataSource3.Fill("INSERT_COD01M00");
                }
                else
                {
                    sqlDataSource3.Queries["UPDATE_COD01M00"].Parameters.Find(x => x.Name == "P_CLIENT_CD").Value = dr["CLIENT_CD"].ToString();

                    sqlDataSource3.Queries["UPDATE_COD01M00"].Parameters.Find(x => x.Name == "P_CLIENT_NM").Value = dr["CLIENT_NM"].ToString();
                    sqlDataSource3.Queries["UPDATE_COD01M00"].Parameters.Find(x => x.Name == "P_TEL_NO").Value = dr["TEL_NO"].ToString();
                    sqlDataSource3.Queries["UPDATE_COD01M00"].Parameters.Find(x => x.Name == "P_FAX_NO").Value = dr["FAX_NO"].ToString();
                    sqlDataSource3.Queries["UPDATE_COD01M00"].Parameters.Find(x => x.Name == "P_DESCRIPT").Value = dr["DESCRIPT"].ToString();


                    SqlDataSource.DisableCustomQueryValidation = true;

                    sqlDataSource3.Fill("UPDATE_COD01M00");
                }

            }
            catch (Exception ex)
            {

                MsgCaption.Caption = ex.InnerException.InnerException.InnerException.Message;
            }
            finally
            {
             //   b_Insert = false;
            }

        }

        private void gridView1_EditFormHidden(object sender, DevExpress.XtraGrid.Views.Grid.EditFormHiddenEventArgs e)
        {

            

        }

        private void gridView1_ValidatingEditor(object sender, DevExpress.XtraEditors.Controls.BaseContainerValidateEditorEventArgs e)
        {
            
        }
    }
}
